{% set data = load_setup_py_data() %}

package:
  name: streamvis
  version: {{ data['version'] }}

source:
  path: ..

build:
  entry_points:
    - streamvis = streamvis.streamvis:main

requirements:
  build:
    - python
    - setuptools
  run:
    - python>=3.6
    - bokeh==0.13.0
    - pyzmq
    - matplotlib
    - pillow>=4.3
    - colorcet
    - h5py

about:
  home: https://github.com/ivan-usov/streamvis
  summary: {{ data['description'] }}
  license: GNU GPLv3
  license_file: LICENSE
