{% set data = load_setup_py_data() %}

package:
  name: streamvis
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  entry_points:
    - streamvis = streamvis.cli:main

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - bokeh=2.2
    - jungfrau_utils=1
    - pyzmq
    - pillow>=4.3
    - colorcet

test:
  source_files:
      - tests
  requires:
      - pytest

about:
  home: https://github.com/paulscherrerinstitute/streamvis
  summary: {{ data['description'] }}
  license: GNU GPLv3
  license_file: LICENSE
