{% set data = load_setup_py_data() %}

package:
  name: streamvis
  version: {{ data['version'] }}

source:
  path: ..

build:
  entry_points:
    - streamvis = streamvis.cli:main

requirements:
  build:
    - python
    - setuptools
  run:
    - python>=3.6
    - bokeh=1.4
    - jungfrau_utils=0.8
    - pyzmq
    - pillow>=4.3
    - colorcet

about:
  home: https://github.com/paulscherrerinstitute/streamvis
  summary: {{ data['description'] }}
  license: GNU GPLv3
  license_file: LICENSE
