{% set data = load_setup_py_data() %}

package:
  name: streamvis
  version: {{ data['version'] }}

source:
  path: ..

build:
  entry_points:
    - streamvis = streamvis.cli:main

requirements:
  build:
    - python
    - setuptools
  run:
    - python>=3.6
    - bokeh==1.1.0
    - pyzmq>=17.0.0
    - pillow>=4.3
    - colorcet>=1.0.0
    - h5py>=2.8.0
    - jungfrau_utils==0.2.5

about:
  home: https://github.com/ivan-usov/streamvis
  summary: {{ data['description'] }}
  license: GNU GPLv3
  license_file: LICENSE
